<template>
  <div>
    <h2 class="title flex align-center">
      <v-btn
        icon
        @click="$emit('close')"
      >
        <v-icon>mdi-arrow-left</v-icon>
      </v-btn>
      {{ $t('sidebar.about.title') }}
    </h2>
    <v-list>
      <v-list-item
        href="https://2metz.fr"
        target="_blank"
        rel="noopener"
      >
        <v-list-item-icon>
          <v-icon>mdi-link</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>{{ $t('sidebar.about.created_by') }}</v-list-item-title>
        </v-list-item-content>
      </v-list-item>
      <v-list-item
        href="https://twitter.com/francois2metz"
        target="_blank"
        rel="noopener"
      >
        <v-list-item-icon>
          <v-icon>mdi-twitter</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>@francois2metz</v-list-item-title>
        </v-list-item-content>
      </v-list-item>
      <v-list-item
        href="https://github.com/indoorequal"
        target="_blank"
        rel="noopener"
      >
        <v-list-item-icon>
          <v-icon>mdi-github</v-icon>
        </v-list-item-icon>
        <v-list-item-content>
          <v-list-item-title>GitHub</v-list-item-title>
        </v-list-item-content>
      </v-list-item>
    </v-list>
  </div>
</template>
