#!/usr/bin/env node

const fetch = require('minipass-fetch');
const deepmerge = require('deepmerge');
const deepsort = require('deepsortobj');
const yaml = require('js-yaml');
const fs = require('fs');

async function fetchData() {
  const res = await fetch('https://raw.githubusercontent.com/indoorequal/indoorequal/master/layers/poi/mapping.yaml');
  return res.text();
}

function updateLocalesFiles(yamlContent) {
  const doc = yaml.load(yamlContent);
  const mapping = doc.tables.poi_point.mapping;
  const keys = Object.keys(mapping);
  const types = keys.reduce((memo, key) => {
    memo[key] = mapping[key].reduce((memo, v) => {
      memo[v] = v;
      return memo;
    }, {});
    return memo;
  }, {});
  const locales = ['en', 'fr'];
  locales.forEach((locale) => {
    const l = require(`../locales/${locale}.json`);
    l.poi = deepsort(deepmerge(types, l.poi));
    fs.writeFileSync(`./locales/${locale}.json`, JSON.stringify(l, null, '  ') + "\n", { encoding: 'utf-8' });
  });
}

function updatePoiMapping(yamlContent) {
  const doc = yaml.load(yamlContent);
  const mapping = doc.tables.poi_point.mapping;
  fs.writeFileSync('./js/preview/poimapping.json', JSON.stringify(mapping, null, '  ') + "\n", { encoding: 'utf-8' });
}

async function main() {
  const yamlContent = await fetchData();
  updateLocalesFiles(yamlContent);
  updatePoiMapping(yamlContent);
}

main();
