#!/bin/sh

DOCKER_RUN="docker run --rm --tty --interactive --user $(id -u):$(id -g) --volume $(pwd):/code --workdir /code --publish 1234:1234 --publish 1235:1235 node:18"

$DOCKER_RUN yarn install
$DOCKER_RUN yarn run dev $@
